In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 =np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])


In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)
#DF of concatenated values

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [10]:
pd.concat([ser1,ser2],keys={'cat1','cat2'})
#Labels each section

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2= DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [12]:
dframe1

X         Y         Z
0 -0.444515 -0.740643  0.077783
1  0.259156 -0.927734 -0.667184
2 -0.158238 -0.725611 -0.286430
3 -0.636538 -1.483166 -0.916384

In [13]:
dframe2

Y         Q         X
0 -0.205291 -1.046569  1.062739
1 -0.466702  0.382627 -1.810475
2  0.380414 -1.157456 -0.040815

In [14]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.444515 -0.740643  0.077783
1       NaN  0.259156 -0.927734 -0.667184
2       NaN -0.158238 -0.725611 -0.286430
3       NaN -0.636538 -1.483166 -0.916384
0 -1.046569  1.062739 -0.205291       NaN
1  0.382627 -1.810475 -0.466702       NaN
2 -1.157456 -0.040815  0.380414       NaN

In [15]:
pd.concat([dframe1,dframe2],ignore_index=True)
#Continious index

Q         X         Y         Z
0       NaN -0.444515 -0.740643  0.077783
1       NaN  0.259156 -0.927734 -0.667184
2       NaN -0.158238 -0.725611 -0.286430
3       NaN -0.636538 -1.483166 -0.916384
4 -1.046569  1.062739 -0.205291       NaN
5  0.382627 -1.810475 -0.466702       NaN
6 -1.157456 -0.040815  0.380414       NaN